name: vca_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python
  - python=3.12
  - pandas
  - numpy
  - matplotlib
  - pysam=0.23
  - pysradb=2.5
  - requests
  - bwa
  - samtools
  - bcftools
  - wget
  - ipykernel
  - ipython
  - jupyter
  - notebook
  - scipy
  - seaborn
  - pyyaml
  - pip
  - pip:
    - primer3-py
    - dna_features_viewer
    - biopython
    - bcbio-gff